### ISSUE TITLE
关于2.3.2版本元素对齐不显示辅助线的问题

### ISSUE THREAD

**Issue by Vegril** [gorkys/vue-draggable-resizable-gorkys#10]
之前用的2.2.0版本,吸附对齐是可以用的,昨天更新到2.3.2版本后看文档中写属性是snap和snap-tolerance,但是我设置了还是不出现辅助线,有什么需要注意的吗?
![image](https://user-images.githubusercontent.com/51567060/69689033-ca4ef380-1102-11ea-9cb5-ebf94c06d878.png)

**Comment by gorkys** [comment]
@Vegril 你在文档页面搜索`refLineParams`，下面有demo代码。

**Comment by Vegril** [comment]
原来如此,太感谢了,我以为下面那个事件是不需要的,抱歉抱歉

**Comment by ccyzz** [comment]
@Vegril请问你的辅助线循环时绑定的key有没有报错，我绑定的是index，但是老是报错

**Comment by Vegril** [comment]
> @Vegril请问你的辅助线循环时绑定的key有没有报错，我绑定的是index，但是老是报错

任何情况下都不推荐绑定index,会导致不可预估的错误,个人做法是手动添加一个id属性,然后绑定这个属性即可.
![image](https://user-images.githubusercontent.com/51567060/70303850-89aa5500-183b-11ea-9c2d-8228a150849b.png)

**Comment by Vegril** [comment]
> @Vegril请问你的辅助线循环时绑定的key有没有报错，我绑定的是index，但是老是报错
`getRefLineParams(params) {
      if (params.vline) {
        for (let i = 0; i < params.vline.length; i++) {
          params.vline[i].id = i;
        }
      }
      if (params.hline) {
        for (let i = 0; i < params.hline.length; i++) {
          params.hline[i].id = i;
        }
      }
      const { vLine, hLine } = params;
      this.vLine = vLine;
      this.hLine = hLine;
    }`

**Comment by ccyzz** [comment]
> > @Vegril请问你的辅助线循环时绑定的key有没有报错，我绑定的是index，但是老是报错
> > `getRefLineParams(params) {       if (params.vline) {         for (let i = 0; i < params.vline.length; i++) {           params.vline[i].id = i;         }       }       if (params.hline) {         for (let i = 0; i < params.hline.length; i++) {           params.hline[i].id = i;         }       }       const { vLine, hLine } = params;       this.vLine = vLine;       this.hLine = hLine;     }`


按照你说的去写，已经解决了，非常感谢！
