### ISSUE TITLE
关于现拖拽元素中对元素进行拖拽的问题

### ISSUE THREAD

**Issue by JaxsonWang** [gorkys/vue-draggable-resizable-gorkys#11]
![QQ截图20191204112107](https://user-images.githubusercontent.com/16836692/70109898-3e9c1080-1688-11ea-9e1f-1b0613eb8bc9.png)
![QQ截图20191204112116](https://user-images.githubusercontent.com/16836692/70109899-3e9c1080-1688-11ea-9999-2614c6ee8f5d.png)

如图展示，只要拖拽元素中的子元素，就会出现错位的问题，如果修改样式 `position: absolute`，会连着把父类元素一起拖动（正常状态应该是父类元素不会拖动，之后改动子元素的位置），请问有什么思路可以解决这个问题？谢谢！

**Comment by ccyzz** [comment]
你好，我加了元素辅助线的对齐，可是并不起作用。请问可能是什么原因呢，下面是我的代码
`<vdr
        v-for="(item, index) in allData"
        :key="index"
        :x="item.x"
        :y="item.y"
        :w="item.width"
        :h="item.height"
        :min-width="200"
        :min-height="200"
        :isActive="true"
        :parent="true"
        :isConflictCheck="true"
        @dragging="onDrag(arguments, item)"
        @resizing="onResize(arguments, item)"
        @refLineParams="getRefLineParams">
      </vdr>
      
      <span class="ref-line v-line"
            v-for="(item, index) in vLine"
            :key="index"
            v-show="item.display"
            :style="{ left: item.position, top: item.origin, height: item.lineLength}"
      />
      <span class="ref-line h-line"
            v-for="(item, index) in hLine"
            :key="index"
            v-show="item.display"
            :style="{ top: item.position, left: item.origin, width: item.lineLength}"
       />
      `
然后在data中定义了vLine和hLine
getRefLineParams方法也是按照demo上来的
`getRefLineParams (line) {
      console.log(line)
      const { vLine, hLine } = line
      this.vLine = vLine
      this.hLine = hLine
    },`

**Comment by gorkys** [comment]
对于这类嵌套使用组件，暂时没有良好的思路。

**Comment by itfei** [comment]
这种嵌套使用组件，现在是暂时没有思路处理吗？有相关的demo吗

**Comment by itfei** [comment]
@JaxsonWang 您那边实现这种拖拽嵌套拖拽了吗

**Comment by JaxsonWang** [comment]
@itfei 目前我用 [interactjs](https://interactjs.io/) 进行封装的，这个支持嵌套拖拽

**Comment by Flourad** [comment]
> [interactjs](https://interactjs.io/)

请问有没有例子参考的，现在也碰到嵌套拖拽的问题，求指教？

**Comment by Flourad** [comment]
> @itfei 目前我用 [interactjs](https://interactjs.io/) 进行封装的，这个支持嵌套拖拽

请问有没有例子参考的，现在也碰到嵌套拖拽的问题，求指教？

**Comment by Flourad** [comment]
> @itfei 目前我用 [interactjs](https://interactjs.io/) 进行封装的，这个支持嵌套拖拽

@JaxsonWang
