### ISSUE TITLE
点击组件，组件会刷新

### ISSUE THREAD

**Issue by ccyzz** [gorkys/vue-draggable-resizable-gorkys#12]
你好，我的组件里面是一个echarts饼图。当我点击组件的时候，饼图会重绘，请问怎样可以阻止饼图重绘

**Comment by gorkys** [comment]
麻烦提供一下在线demo,不然无法确认是否因组件而导致的重绘。

**Comment by ccyzz** [comment]
谢谢，我已经找到原因了

**Comment by qiangwai** [comment]
> 谢谢，我已经找到原因了
什么原因呢
