### ISSUE TITLE
多个活动组件切换的过程中组件的data没有变化，但是位置发生的偏移

### ISSUE THREAD

**Issue by jasonSource** [gorkys/vue-draggable-resizable-gorkys#15]
![image](https://user-images.githubusercontent.com/54168614/71052991-0d433a80-2188-11ea-8d42-d2cf9d657a51.png)
我有多个屏幕进行切换，里面包含活动组件，当我在右边切换屏幕的时候，（所有屏幕在一个data里）组件的尺寸位置信息没有变化，但是在页面上发生了偏移，和所包含的数据不一致，请问一下这是什么原因，切换过程中数据是不变的

**Comment by gorkys** [comment]
可能是因为数据冲突？其实这种情况基本只能靠自己调试。
