### ISSUE TITLE
请教一下如何进行从外界拖拽生成组件。

### ISSUE THREAD

**Issue by chen-ABC** [gorkys/vue-draggable-resizable-gorkys#18]
![image](https://user-images.githubusercontent.com/30097790/71468300-69e5cb80-2800-11ea-964e-33ef92bc8276.png)
类似鼠标在输入框文本处按下，自动生成组件并可以拖拽。 我试过按下时进行数组push，组件生成但是没有被默认选中无法进行拖拽。使用js主动触发mousedown发现会产生极大偏移。
![image](https://user-images.githubusercontent.com/30097790/71468387-baf5bf80-2800-11ea-858f-a327c638815b.png)

**Comment by gorkys** [comment]
你这个代码不全面，并不知道你在`template`中写了哪些属性。
https://github.com/gorkys/koa-demo/blob/web/src/components/templateMake/index.vue这里实现了点击某个点就生成一个组件的功能。不太好查看的话直接搜索`addElement`这个方法。

**Comment by chen-ABC** [comment]
@gorkys  感谢回答。我这边的疑问是：生成新组件没有问题，但是生成的同时不允许我直接拖拽，还要我手动点击新组件再拖拽。类似这种效果 https://sortablejs.github.io/Vue.Draggable/#/clone（但是它不支持任意拖拽） 我查看了您的代码似乎也没有实现这种效果

**Comment by gorkys** [comment]
你的意思是根据鼠标松开的位置进行放置组件么？

**Comment by chen-ABC** [comment]
@gorkys 是的, 就是这样的效果，感谢你的回答，按照你的提示，我可以先做一个假的组件在鼠标下方，最后再真正的插入组件里面

**Comment by gorkys** [comment]
是的，这种需要自己模拟，然后根据鼠标位置进行生成～


 
---原始邮件---
发件人: "abc"<notifications@github.com&gt;
发送时间: 2019年12月26日 18:35:25
收件人: "gorkys/vue-draggable-resizable-gorkys"<vue-draggable-resizable-gorkys@noreply.github.com&gt;;
抄送: "Gorkys"<king@tingtas.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [gorkys/vue-draggable-resizable-gorkys] 请教一下如何进行从外界拖拽生成组件。 (#18)



@gorkys 是的, 就是这样的效果，感谢你的回答，按照你的提示，我可以先做一个假的组件在鼠标下方，最后再真正的插入组件里面

**Comment by itfei** [comment]
@chen-ABC 你们的项目实现嵌套的写法了吗？

**Comment by gorkys** [comment]
@itfei 
>你可以监听事件,里面写了拖拽的事件，然后获取宽高 改变子级
这是一群友给出的方案。
