### ISSUE TITLE
parent allowed .class identifier, now its boolean only.

### ISSUE THREAD

**Issue by jaketoolson** [gorkys/vue-draggable-resizable-gorkys#2]
Love the additional features you have added :)

Previously, I could use parent to identify a class to restrict the draggable to.  Now, it only allows boolean.  Any plans on restoring the previous capability to also allow css class?

**Comment by gorkys** [comment]
I am glad that you can love the additional features of the component, but the features you mentioned I have not found in the previous version, and did not encounter the corresponding usage scenarios. So there is no related plan to join the css class.
If you can modify a version and `pull requests`, I will consider merging it without affecting other features.

**Comment by jaketoolson** [comment]
The previous version and documentation is from https://github.com/mauricius/vue-draggable-resizable#parent

**Comment by gorkys** [comment]
@jaketoolson 
The type of `parent` in the source code is defined as `Boolean`, which is only used as a condition for judging, and it has not been found to function as a selector.
Sorry, I have not tested successfully. Maybe I made a mistake?
