### ISSUE TITLE
缺少计算属性

### ISSUE THREAD

**Issue by LiuQMadmin** [gorkys/vue-draggable-resizable-gorkys#23]
屏幕宽度动态变宽后，每一个拖动的元素w,h,x,y不会重新计算

**Comment by gorkys** [comment]
可参考[demo](https://tingtas.com/vue-draggable-resizable-gorkys/?path=/story/%E7%88%B6%E7%BA%A7--%E7%88%B6%E7%BA%A7%E5%9F%BA%E6%9C%AC%E6%A1%88%E4%BE%8B)
