### ISSUE TITLE
您好,除了改写没有提供父组件直接修改内部宽高及位置的方法吗?

### ISSUE THREAD

**Issue by Sercl** [gorkys/vue-draggable-resizable-gorkys#24]
您好,除了改写没有提供父组件直接修改内部宽高及位置的方法吗?修改prop传进去的参数无效.
将来有计划增加吗?感谢

**Comment by gorkys** [comment]
不好意思，没有理解到你这句话的问题。

**Comment by Sercl** [comment]
> 不好意思，没有理解到你这句话的问题。

就是比如在A组件(A是父组件,draggbale是子组件)中通过this.$refs.draggbale.x(50).然后将draggbale定位到X轴50像素.父组件通过修改prop传进去的x,y,w,h参数并不能实时正常改变draggbale的位置及大小

**Comment by gorkys** [comment]
我想你应该是说的通过外部修改参数从而改变组件大小与位置？你参考一下这个[Demo](https://tingtas.com/vue-draggable-resizable-gorkys/?path=/info/%E5%9F%BA%E6%9C%AC--%E5%9F%BA%E6%9C%AC%E6%8E%A7%E5%88%B6%E7%BB%84%E4%BB%B6)呢？

**Comment by Sercl** [comment]
非常感谢,改变prop传入的xyhw不能正常改变是因为设置了网格,必须得达到网格最小长度才能正常改变位置宽高
