### ISSUE TITLE
onDeactivated 点击任意地方组件都取消，可否设置成只点击可拖动区域生效

### ISSUE THREAD

**Issue by Shangri-GitHub** [gorkys/vue-draggable-resizable-gorkys#26]
@deactivated="onDeactivated" 这个方法太讨厌了，点击任意地方组件都取消，能不能设置成点击可拖动的区域点击才能取消？？？？？

**Comment by gorkys** [comment]
加个判断，如果不是在所需区域的`click`就使用`active`属性重新激活当前组件。

**Comment by lhtuling** [comment]
碰到同样问题+1 自己没搞定，希望大佬搞好的代码能参考下~~感谢
