### ISSUE TITLE
parent 为true 是否可以只设置parentW或者parentH吗

### ISSUE THREAD

**Issue by txlwll** [gorkys/vue-draggable-resizable-gorkys#29]
parent 为true 是否可以只设置parentW或者parentH吗？比如只限制水平方向不能拖出父组件，数值方向可以拖出父组件，只能向下拖组件

**Comment by gorkys** [comment]
使用`axis` prop来控制可拖动的轴。 合适的值是x，y或both。
再配合`parent`应该可以实现你想要的效果。

**Comment by txlwll** [comment]
您好，按照您的建议，我设置了parent 为false，当x<0时设置axis = ‘y’；这样它是不能往左移动了，但是往右也移动不了了，还是我没有设置对参数

**Comment by gorkys** [comment]
参数只能限制到水平或垂直。

**Comment by Flourad** [comment]
> 参数只能限制到水平或垂直。

请问还有别的办法可以控制只能垂直方向上超出拖动么？
