### ISSUE TITLE
请教一下做辅助线的思路，不胜感激。

### ISSUE THREAD

**Issue by kybetter** [gorkys/vue-draggable-resizable-gorkys#41]

**Comment by gorkys** [comment]
当前激活的组件与其它兄弟元素进行比较，如果边界存在1px触碰就显示辅助线。辅助线分为x轴三根，Y轴三根，长度是根据最远距离重合的两个组件计算得出来的。具体可以翻阅一下代码，也是借鉴了别人组件的思路改出来的。
