### ISSUE TITLE
辅助线出现虚影是什么原因

### ISSUE THREAD

**Issue by raohuiyong** [gorkys/vue-draggable-resizable-gorkys#65]
已经停止拖拽和激活状态了，但是出现了虚影
![image](https://user-images.githubusercontent.com/26049430/125041217-17f75480-e0cb-11eb-896c-2232aee1b823.png)

**Comment by gorkys** [comment]
情况不明，原组件也会出现类似问题，可能是浏览器渲染方面的问题。
