### ISSUE TITLE
启动项目报 找不到core-js的错

### ISSUE THREAD

**Issue by youzhidong** [gorkys/vue-draggable-resizable-gorkys#7]
我 install  core-js但是还是报not found: Error: Can't resolve 'core-js/modules/es6.array.filter'

**Comment by gorkys** [comment]
你可能需要把`package-lock.json`与`node_modules`文件夹删除，然后再`npm install`

**Comment by youzhidong** [comment]
我重新npm install了，用npm run serve启动还是报core-js/modules/es6.array.filter

**Comment by gorkys** [comment]
`npm install core-js@2`试试。

**Comment by youzhidong** [comment]
启动cnpm install core-js@2.6.9 -D  完美解决，非常感谢

**Comment by gorkys** [comment]
按理说，你删除`package-lock.json`再安装就应该可以了的，因为`core-js`是在最新一个版本中有意删除。安装只是因为同步原作者的依赖版本时的一个解决方案。
