### ISSUE TITLE
关于vue-draggable-resizable-gorkys的版本是否同步到npm上

### ISSUE THREAD

**Issue by ccyzz** [gorkys/vue-draggable-resizable-gorkys#9]
请问最新版本已经更新到npm上了吗，npm install vue-draggable-resizable-gorkys 下载下来的东西内容不全

**Comment by gorkys** [comment]
@ccyzz 现在最新版本应该是2.3.1，你看一下。

**Comment by Vegril** [comment]
提示找不到文件

**Comment by ccyzz** [comment]
好像是因为下载下来的模块里缺少很多文件，css，js这些文件都没有

**Comment by gorkys** [comment]
@ccyzz @Vegril 先确认一下是否是2.3.1版本，昨天晚上发布的2.3.0版本是有问题的。

**Comment by ccyzz** [comment]
看了一下，是2.3.1版本的，"vue-draggable-resizable-gorkys": "^2.3.1"

**Comment by Vegril** [comment]
是2.3.1版本的

**Comment by gorkys** [comment]
@ccyzz @Vegril 好的，非常感谢，我找一下原因，你们可以先用2.2.x的吧

**Comment by Vegril** [comment]
嗯嗯,已回退到2.2.0

**Comment by ccyzz** [comment]
麻烦解决了告诉我一声，谢谢啦！

**Comment by gorkys** [comment]
@ccyzz @Vegril 已更新发布，2.3.2版本。

**Comment by ccyzz** [comment]
刚刚安装了一下，好了，可以用

**Comment by Vegril** [comment]
这个元素对齐辅助线可以用吗

**Comment by gorkys** [comment]
@Vegril 最新版本是可以的。

**Comment by Vegril** [comment]
需要设置snap和snap-tolerance是吗

**Comment by gorkys** [comment]
@Vegril 是的。

**Comment by Vegril** [comment]
但是为什么我设置之后不显示辅助线呢,对齐效果是有的

**Comment by gorkys** [comment]
@Vegril 去看文档

**Comment by ccyzz** [comment]
@gorkys 我想在这个事件resizing(x,y,width,height)中添加我需要的参数，还要保留原有的参数(x,y,width,height)，我是这样resizing(params, $event)写的，但是只能保留参数中的x。请问我怎样写可以把所有的参数都保留下来

**Comment by gorkys** [comment]
@ccyzz `resizing(arguments,$event)`
<https://github.com/vuejs/vue/issues/5735>

**Comment by ccyzz** [comment]
明白了，感谢！
